EXTENSION = pgs_json        # the extensions name
DATA = pgs_json--0.1.sql  # script files to install

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)